version: "2.1"
services:
  phets-api:
    container_name: phets-api
    image: phetsunal/phets-api:latest
    environment:
      PORT: "4000"
      SHOW_URLS: "true"
      EVENT_URL: "phets-event-ms"
      EVENT_PORT: "4001"
      EVENT_ENTRY: "event"
      CHAT_URL: "172.17.0.1"
      CHAT_PORT: "4002"
      ANIMAL_URL: "phets-animal-ms"
      ANIMAL_PORT: "4003"
      INTERACTION_URL: "phets-interaction-ms"
      INTERACTION_PORT: "4005"
      INTERACTION_ENTRY: "api/interaction"
      NOTIFICATION_URL: "phets-notification-ms"
      NOTIFICATION_PORT: "4004"
      NOTIFICATION_ENTRY: "notifications"
      USER_URL: "phets-users-ms"
      USER_PORT: "4006"
  phets-users-ms:
    container_name: phets-users-ms
    image: phetsunal/phets-users-ms:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.17.0.1:3006/user?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: phets-user
      SPRING_DATASOURCE_PASSWORD: phets-password
    depends_on:
      phets-users-db:
        condition: service_healthy
    healthcheck:
      test: "curl -I phets-users-ms:4006/user --fail"
      interval: 20s
      retries: 10
  phets-users-db:
    image: mysql:5.7
    container_name: phets-users-db
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    volumes:
      - phets-users-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ph375-u53r5
      MYSQL_DATABASE: user
      MYSQL_USER: phets-user
      MYSQL_PASSWORD: phets-password
    ports:
      - "3006:3306"
  phets-animal-ms:
    container_name: phets-animal-ms
    image: phetsunal/phets-animal-ms:latest
    depends_on:
      phets-animal-db:
        condition: service_healthy
    environment:
      DATABASE_USER: animalUser
      DATABASE_PASS: password
      DATABASE_URI: 172.17.0.1:3003
      DATABASE_NAME: animals
  phets-animal-db:
    image: mysql:5.7
    container_name: phets-animal-db
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    volumes:
      - phets-animal-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: animals123
      MYSQL_DATABASE: animals
      MYSQL_USER: animalUser
      MYSQL_PASSWORD: password
    ports:
      - "3003:3306"
  phets-file-ms:
    container_name: phets-file-ms
    image: phetsunal/phets-file-ms:latest
    volumes:
      - phets-files-volume:/var/local/uploads
    environment:
      PORT: "4007"
      UPLOADS_PATH: "/var/local/uploads"
  phets-event-ms:
    container_name: phets-event-ms
    image: phetsunal/phets-event-ms
    depends_on:
      phets-event-db:
        condition: service_healthy
    environment:
      PORT: 4001
      MONGO_HOST: 172.17.0.1
      MONGO_PORT: 3001
    healthcheck:
      test: "curl -G localhost:8000/event --fail"
      interval: 20s
      retries: 10
  phets-event-db:
    container_name: phets-event-db
    image: mongo
    volumes:
      - phets-event-db-volume:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 20s
      timeout: 5s
      retries: 3
    ports:
      - "3001:27017"
  phets-interaction-ms:
    container_name: phets-interaction-ms
    image: phetsunal/phets-interaction-ms
    depends_on:
      - "phets-interaction-db"
    environment:
      DB_CONNECTION_STRING: "host=phets-interaction-db;port=5432;database=interaction_db;username=phets_interaction;password=phets_interaction"
  phets-interaction-db:
    container_name: phets-interaction-db
    image: postgres:11
    ports:
      - "3005:5432"
    restart: always
    volumes:
      - ./dbscripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - phets-interaction-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "phets_interaction"
      POSTGRES_PASSWORD: "phets_interaction"
      POSTGRES_DB: "interaction_db"
  phets-notification-ms:
    container_name: phets-notification-ms
    image: phetsunal/phets-notification-ms
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:create db:migrate && bundle exec rails s -p 4004 -b '0.0.0.0'"
    depends_on:
      - phets-notification-db
  phets-notification-db:
    container_name: phets-notification-db
    image: postgres
    volumes:
      - phets-notification-db-volume:/var/lib/postgresql/data
    ports:
      - "3004:5432"
  phets-web:
    container_name: phets-web
    image: phetsunal/phets-web
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 5000
  phets-soa-interface:
    container_name: phets-soa-interface
    image: phetsunal/phets-soa-interface
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails s -p 4008 -b '0.0.0.0'"
    environment:
      EVENT_MS_HOST: 172.17.0.1
      EVENT_MS_PORT: 4001
    ports:
      - "4008:4008"
  phets-proxy:
    image: phetsunal/phets-proxy
    depends_on:
      - phets-api
    ports:
      - "80:80"

volumes:
  phets-animal-volume:
  phets-files-volume:
  phets-users-db:
  phets-interaction-volume:
  phets-notification-db-volume:
  phets-event-db-volume:
