version: "3"
services:
  phets-notification-db:
    image: postgres
    volumes:
      - phets-notification-db-volume:/var/lib/postgresql/data
    ports:
      - "3004:5432"
  phets-notification-ms:
    image: phets/phets-notification-ms
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:create db:migrate && bundle exec rails s -p 4004 -b '0.0.0.0'"
    # volumes:
    #   - .:/sa_notification_ms
    ports:
      - "4004:4004"
    depends_on:
      - phets-notification-db

volumes:
  phets-notification-db-volume:
