version: "3.4"

networks:
  phets-interaction-ms-dev:
    driver: bridge

services:
  postgres_image:
    image: postgres:11
    ports:
      - "3005:5432"
    restart: always
    volumes:
      - ./dbscripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "phets_interaction"
      POSTGRES_PASSWORD: "phets_interaction"
      POSTGRES_DB: "interaction_db"
    networks:
      - phets-interaction-ms-dev

  phets-interaction-ms:
    image: phetsunal/phets-interaction-ms
    depends_on:
      - "postgres_image"
    ports:
      - "4005:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=interaction_db;username=phets_interaction;password=phets_interaction"
    networks:
      - phets-interaction-ms-dev
