version: "3.4"
services:
  phets-interaction-db:
    container_name: phets-interaction-db
    image: postgres:latest
    ports:
      - "3005:5432"
    restart: always
    volumes:
      - phets-interaction-volume:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "phets_interaction"
      POSTGRES_PASSWORD: "phets_interaction"
      POSTGRES_DB: "interaction_db"
    networks:
      - interaction_ms-dev
  phets-interaction-ms:
    container_name: phets-interaction-ms
    image: phetsunal/phets-interaction-ms
    depends_on:
      - "phets-interaction-db"
    ports:
      - "4005:80"
    environment:
      DB_CONNECTION_STRING: "host=phets-interaction-db;port=3005;database=interaction_db;username=phets_interaction;password=phets_interaction"
    networks:
      - interaction_ms-dev

volumes:
  phets-interaction-volume:

networks:
  interaction_ms-dev:
    driver: bridge